### ISSUE TITLE
How do i use this recipe? I cant find installation for ferdi-notion.

### ISSUE THREAD

**Issue by rikikamano** [TanZng/ferdi-notion#1]

**Comment by TanZng** [comment]
1. Click on Download ZIP 
2. On Ferdi click on Add new service and go to Custom Service
3. Click on Open Folder
4. In the folder that Ferdi opened for you (ex. ...\Ferdi\recipes\dev), drag the unzip ferdi-notion folder
5. After that Notion should appear on Custom Services. If not, restart Ferdi.
